from __future__ import annotations

import json
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


class ArchitectureExporter:
    """Generates all 12 output formats from a single architecture object.

    Formats:
    1. JSON artifacts (all schemas)
    2. Markdown PRDs (master + components)
    3. Interactive HTML atlas
    4. Adaptive prototype HTML
    5. Simulation dashboard HTML
    6. Executive summary PDF (placeholder)
    7. Technical architecture diagram (Mermaid)
    8. Analytics instrumentation spec
    9. Outcome cascade visualization
    10. AI layer plan
    11. Experience plan
    12. PM Briefing with confidence levels
    """

    def export_all(
        self,
        architecture: Dict[str, Any],
        *,
        gaps: Optional[List[Dict[str, Any]]] = None,
        forecast: Optional[Dict[str, Any]] = None,
        domain_activation: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, str]:
        """Generate all 12 output formats.

        Returns:
            ExportBundle dict mapping format name to generated content string
        """
        bundle: Dict[str, str] = {}
        gaps = gaps or []
        forecast = forecast or {}
        domain_activation = domain_activation or {}

        bundle["json_artifacts"] = self._export_json(architecture)
        bundle["markdown_prds"] = self._export_markdown_prds(architecture)
        bundle["html_atlas"] = self._export_html_atlas(architecture)
        bundle["html_prototype"] = self._export_adaptive_prototype(architecture)
        bundle["html_simulation"] = self._export_simulation_dashboard(architecture)
        bundle["executive_summary_pdf"] = self._export_executive_summary(architecture)
        bundle["mermaid_diagram"] = self._export_mermaid_diagram(architecture)
        bundle["analytics_spec"] = self._export_analytics_spec(architecture)
        bundle["outcome_cascade"] = self._export_outcome_cascade(architecture)
        bundle["ai_layer_plan"] = self._export_ai_layer_plan(architecture)
        bundle["experience_plan"] = self._export_experience_plan(architecture)
        bundle["pm_briefing"] = self._export_pm_briefing(
            architecture,
            gaps,
            forecast,
            domain_activation,
        )

        return bundle

    def _export_json(self, architecture: Dict[str, Any]) -> str:
        """1. JSON artifacts for system consumption."""
        export = {
            "product_architecture": architecture.get("product_architecture_id", ""),
            "artifacts": architecture.get("artifacts", []),
            "persona_archetype_pack": architecture.get("persona_archetype_pack", {}),
            "workflow_orchestration_map": architecture.get("workflow_orchestration_map", {}),
            "component_prds": architecture.get("component_prds", []),
            "customer_journey_maps": architecture.get("customer_journey_maps", []),
            "api_contract_hypotheses": architecture.get("api_contract_hypotheses", []),
            "zoom_navigation_map": architecture.get("zoom_navigation_map", {}),
            "cross_links": architecture.get("cross_links", []),
        }
        return json.dumps(export, indent=2)

    def _export_markdown_prds(self, architecture: Dict[str, Any]) -> str:
        """2. Markdown PRDs for human review."""
        lines = [
            "# Product Architecture — Markdown PRD Export",
            "",
            f"**Architecture ID:** {architecture.get('product_architecture_id', 'N/A')}",
            f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
            "",
        ]

        master_prd = next((a for a in architecture.get("artifacts", []) if a["type"] == "master_prd"), None)
        if master_prd:
            lines.extend([
                "## Master PRD",
                "",
                f"- **ID:** {master_prd.get('uuid', 'N/A')}",
                f"- **Type:** {master_prd.get('type', 'N/A')}",
                f"- **Confidence:** {master_prd.get('confidence_metadata', {}).get('overall_confidence', 'N/A')}",
                "",
            ])

        lines.append("## Component PRDs\n")
        for c in architecture.get("component_prds", []):
            lines.extend([
                f"### {c.get('component_name', 'Unnamed Component')}",
                "",
                f"- **ID:** {c.get('component_prd_id', 'N/A')}",
                f"- **Summary:** {c.get('summary', 'No summary')}",
                f"- **Personas:** {', '.join(c.get('assigned_personas', []))}",
                "",
            ])

        lines.append("---\n*Generated by ProductOS V14 ArchitectureExporter*")
        return "\n".join(lines)

    def _export_html_atlas(self, architecture: Dict[str, Any]) -> str:
        """3. Interactive HTML atlas with zoom navigation."""
        zoom_map = architecture.get("zoom_navigation_map", {})
        levels = zoom_map.get("levels", [])

        nav_items = []
        for level in levels:
            entries_html = "".join(
                f'<li><a href="#" data-id="{e["id"]}">{e["title"]}</a></li>'
                for e in level.get("entries", [])
            )
            nav_items.append(
                f'<div class="zoom-level"><h3>{level["label"]}</h3><ul>{entries_html}</ul></div>'
            )

        return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Product Atlas — Interactive Navigation</title>
<style>
  body {{ font-family: system-ui, -apple-system, sans-serif; margin: 2rem; background: #f8f9fa; }}
  .zoom-level {{ background: white; border-radius: 8px; padding: 1rem; margin: 1rem 0; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
  .zoom-level h3 {{ margin: 0 0 0.5rem; color: #1a73e8; }}
  .zoom-level ul {{ list-style: none; padding: 0; }}
  .zoom-level li {{ padding: 0.25rem 0; }}
  .zoom-level a {{ color: #333; text-decoration: none; }}
  .zoom-level a:hover {{ color: #1a73e8; text-decoration: underline; }}
  .breadcrumb {{ padding: 0.5rem 0; color: #666; }}
</style>
</head>
<body>
  <h1>Product Atlas</h1>
  <div class="breadcrumb">Product &gt; Persona &gt; Component &gt; Story</div>
  <div id="atlas-container">{"".join(nav_items)}</div>
  <script>
    document.querySelectorAll('.zoom-level a').forEach(function(el) {{
      el.addEventListener('click', function(e) {{
        e.preventDefault();
        alert('Navigate to: ' + this.dataset.id);
      }});
    }});
  </script>
  <footer><p>Generated by ProductOS V14</p></footer>
</body>
</html>"""

    def _export_adaptive_prototype(self, architecture: Dict[str, Any]) -> str:
        """4. Adaptive prototype HTML with persona role switcher."""
        personas = []
        for a in architecture.get("persona_archetype_pack", {}).get("archetypes", []):
            personas.append({"id": a["persona_ref"], "label": a.get("label", a["persona_ref"])})

        persona_options = "".join(
            f'<option value="{p["id"]}">{p["label"]}</option>' for p in personas
        )

        return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Adaptive Prototype — Persona Role Switcher</title>
<style>
  body {{ font-family: system-ui, sans-serif; margin: 2rem; }}
  .toolbar {{ background: #1a73e8; color: white; padding: 1rem; border-radius: 8px; margin-bottom: 2rem; }}
  .toolbar select {{ padding: 0.5rem; border-radius: 4px; border: none; margin-left: 1rem; }}
  .viewport {{ background: white; border-radius: 8px; padding: 2rem; box-shadow: 0 2px 8px rgba(0,0,0,0.1); min-height: 300px; }}
</style>
</head>
<body>
  <div class="toolbar">
    <strong>Viewing as:</strong>
    <select id="persona-switcher" onchange="switchPersona(this.value)">{persona_options}</select>
    <span id="persona-label" style="margin-left: 1rem;"></span>
  </div>
  <div class="viewport" id="prototype-viewport">
    <h2>Prototype View</h2>
    <p>Select a persona above to see their tailored experience.</p>
  </div>
  <script>
    function switchPersona(personaId) {{
      document.getElementById('persona-label').textContent = 'Persona: ' + personaId;
      document.getElementById('prototype-viewport').innerHTML =
        '<h2>Experience for ' + personaId + '</h2><p>Personalized screens, navigation, and actions for this role.</p>';
    }}
  </script>
  <footer><p>Generated by ProductOS V14</p></footer>
</body>
</html>"""

    def _export_simulation_dashboard(self, architecture: Dict[str, Any]) -> str:
        """5. Simulation dashboard HTML with animated workflow."""
        workflow = architecture.get("workflow_orchestration_map", {})
        handoffs = workflow.get("handoffs", [])

        handoff_rows = "".join(
            f'<tr><td>{h["handoff_id"]}</td><td>{h.get("source_persona", "?")}</td>'
            f'<td>{h.get("target_persona", "?")}</td><td>{h.get("sla_target_seconds", "N/A")}s</td>'
            f'<td style="color:{"green" if h.get("sla_target_seconds", 3600) > 0 else "red"};">●</td></tr>'
            for h in handoffs
        )

        return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Simulation Dashboard</title>
<style>
  body {{ font-family: system-ui, sans-serif; margin: 2rem; background: #1a1a2e; color: #eee; }}
  .dashboard {{ display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }}
  .card {{ background: #16213e; border-radius: 8px; padding: 1rem; }}
  .card h3 {{ color: #0f3460; }}
  table {{ width: 100%; border-collapse: collapse; }}
  th, td {{ padding: 0.5rem; text-align: left; border-bottom: 1px solid #333; }}
  .heatmap {{ display: flex; gap: 0.25rem; }}
  .heatmap-cell {{ width: 20px; height: 20px; border-radius: 2px; }}
</style>
</head>
<body>
  <h1>Workflow Simulation Dashboard</h1>
  <div class="dashboard">
    <div class="card">
      <h3>Handoff Map</h3>
      <table><thead><tr><th>Handoff</th><th>Source</th><th>Target</th><th>SLA</th><th>Status</th></tr></thead>
      <tbody>{handoff_rows}</tbody></table>
    </div>
    <div class="card">
      <h3>Bottleneck Heat Map</h3>
      <p>Handoff-level predicted wait times visualized.</p>
    </div>
  </div>
  <footer><p>Generated by ProductOS V14</p></footer>
</body>
</html>"""

    def _export_executive_summary(self, architecture: Dict[str, Any]) -> str:
        """6. Executive summary PDF (markdown placeholder)."""
        workflow_map = architecture.get("workflow_orchestration_map", {})
        persona_pack = architecture.get("persona_archetype_pack", {})
        num_personas = len(persona_pack.get("archetypes", []))
        num_handoffs = len(workflow_map.get("handoffs", []))

        summary_lines = [
            "Executive Summary - Product Architecture",
            f"Architecture ID: {architecture.get('product_architecture_id', 'N/A')}",
            f"Personas: {num_personas}",
            f"Handoffs: {num_handoffs}",
            f"Components: {len(architecture.get('component_prds', []))}",
            f"Journey Maps: {len(architecture.get('customer_journey_maps', []))}",
            f"API Contracts: {len(architecture.get('api_contract_hypotheses', []))}",
            "",
            "Key Insights",
            "1. Multi-persona workflow orchestration with cross-layer traceability",
            "2. Compliance gates and regulatory overlays are explicitly surfaced",
            "3. The architecture is ready for simulation, review, and PM briefing",
        ]
        return self._render_minimal_pdf("\n".join(summary_lines))

    def _render_minimal_pdf(self, text: str) -> str:
        lines = [line[:90] for line in text.splitlines() if line.strip()]
        if not lines:
            lines = ["ProductOS Executive Summary"]
        content_lines = ["BT", "/F1 12 Tf", "50 780 Td"]
        for index, line in enumerate(lines):
            safe = line.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
            if index == 0:
                content_lines.append(f"({safe}) Tj")
            else:
                content_lines.append("0 -18 Td")
                content_lines.append(f"({safe}) Tj")
        content_lines.append("ET")
        stream = "\n".join(content_lines) + "\n"

        objects = [
            "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
            "2 0 obj\n<< /Type /Pages /Count 1 /Kids [3 0 R] >>\nendobj\n",
            "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj\n",
            "4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
            f"5 0 obj\n<< /Length {len(stream.encode('ascii'))} >>\nstream\n{stream}endstream\nendobj\n",
        ]

        pdf_parts = ["%PDF-1.4\n"]
        offsets = [0]
        current_length = len(pdf_parts[0].encode("ascii"))
        for obj in objects:
            offsets.append(current_length)
            pdf_parts.append(obj)
            current_length += len(obj.encode("ascii"))

        xref_offset = current_length
        xref = [f"xref\n0 {len(offsets)}\n", "0000000000 65535 f \n"]
        for offset in offsets[1:]:
            xref.append(f"{offset:010d} 00000 n \n")
        trailer = (
            f"trailer\n<< /Size {len(offsets)} /Root 1 0 R >>\n"
            f"startxref\n{xref_offset}\n%%EOF\n"
        )
        pdf_parts.extend(xref)
        pdf_parts.append(trailer)
        return "".join(pdf_parts)

    def _export_mermaid_diagram(self, architecture: Dict[str, Any]) -> str:
        """7. Technical architecture diagram in Mermaid format."""
        lines = ["graph TD"]
        persona_pack = architecture.get("persona_archetype_pack", {})
        workflow_map = architecture.get("workflow_orchestration_map", {})
        component_prds = architecture.get("component_prds", [])

        for a in persona_pack.get("archetypes", []):
            pid = a["persona_ref"].replace("-", "_")
            lines.append(f"    {pid}[{a.get('label', pid)}]")

        for h in workflow_map.get("handoffs", []):
            src = h["source_persona"].replace("-", "_")
            tgt = h["target_persona"].replace("-", "_")
            lines.append(f"    {src} -->|{h.get('shared_artifact', 'handoff')}| {tgt}")

        for c in component_prds:
            cid = c.get("component_prd_id", "").replace("-", "_")[:20]
            lines.append(f"    {cid}[{c.get('component_name', cid)[:30]}]")

        return "\n".join(lines)

    def _export_analytics_spec(self, architecture: Dict[str, Any]) -> str:
        """8. Analytics instrumentation spec."""
        workflow_map = architecture.get("workflow_orchestration_map", {})
        handoffs = workflow_map.get("handoffs", [])

        events = []
        for h in handoffs:
            events.append({
                "event": f"handoff.{h['handoff_id']}.initiated",
                "trigger": f"{h['source_persona']} initiates {h['shared_artifact']}",
                "properties": ["handoff_id", "source_persona", "target_persona", "timestamp"],
            })
            events.append({
                "event": f"handoff.{h['handoff_id']}.completed",
                "trigger": f"{h['target_persona']} receives {h['shared_artifact']}",
                "properties": ["handoff_id", "source_persona", "target_persona", "duration_ms", "timestamp"],
            })

        return json.dumps({
            "event_taxonomy": events,
            "metrics": [
                {"name": "handoff_completion_time", "aggregation": "p50/p90/p95", "alert_threshold": "p95 > SLA"},
                {"name": "bottleneck_frequency", "aggregation": "count_per_handoff", "alert_threshold": ">10%"},
            ],
            "dashboards": [
                {"audience": "PM", "widgets": ["handoff_completion_times", "bottleneck_heatmap", "sla_violation_rate"]},
                {"audience": "executive", "widgets": ["overall_workflow_health", "bottleneck_summary"]},
            ],
        }, indent=2)

    def _export_outcome_cascade(self, architecture: Dict[str, Any]) -> str:
        """9. Outcome cascade visualization."""
        return json.dumps({
            "cascade": [
                {
                    "level": "Business Outcome",
                    "entries": [{"id": "bo_001", "description": "Improve workflow efficiency", "confidence": "inferred"}],
                },
                {
                    "level": "Product Outcome",
                    "entries": [{"id": "po_001", "description": "Reduce handoff completion time by 40%", "confidence": "inferred"}],
                },
                {
                    "level": "Feature Metric",
                    "entries": [{"id": "fm_001", "description": "Average handoff completion time", "measurement": "seconds"}],
                },
                {
                    "level": "User Action",
                    "entries": [{"id": "ua_001", "description": "Persona initiates handoff workflow"}],
                },
            ],
        }, indent=2)

    def _export_ai_layer_plan(self, architecture: Dict[str, Any]) -> str:
        """10. AI layer plan."""
        workflow_map = architecture.get("workflow_orchestration_map", {})
        handoffs = workflow_map.get("handoffs", [])

        automation_candidates = []
        for h in handoffs:
            automation_candidates.append({
                "handoff_id": h["handoff_id"],
                "automation_approach": "AI-assisted review",
                "estimated_roi": "40% reduction in processing time",
                "confidence": 0.7,
            })

        return json.dumps({
            "automation_candidates": automation_candidates,
            "human_in_the_loop_checkpoints": [
                {"stage": "compliance_gate", "approval_required": True},
            ],
            "consent_flows": [
                {"where": "phi_data_access", "opt_out_path": "/settings/privacy"},
            ],
        }, indent=2)

    def _export_experience_plan(self, architecture: Dict[str, Any]) -> str:
        """11. Experience plan."""
        persona_pack = architecture.get("persona_archetype_pack", {})

        device_contexts = []
        for a in persona_pack.get("archetypes", []):
            device_contexts.append({
                "persona": a["persona_ref"],
                "primary_device": "desktop",
                "offline_capability": False,
                "accessibility": "WCAG 2.1 AA",
            })

        return json.dumps({
            "per_persona_device_context": device_contexts,
            "progressive_enhancement": [
                {"base": "web", "enhanced": "native_app", "trigger": "offline_needed"},
            ],
            "performance_targets": {
                "load_time_seconds": 3.0,
                "interaction_time_seconds": 1.0,
            },
        }, indent=2)

    def generate_pm_briefing(
        self,
        architecture: Dict[str, Any],
        gaps: List[Dict[str, Any]],
        forecast: Dict[str, Any],
        domain_activation: Dict[str, Any],
    ) -> str:
        """12. PM Briefing — structured summary with confidence levels."""
        return self._export_pm_briefing(architecture, gaps, forecast, domain_activation)

    def _export_pm_briefing(
        self,
        architecture: Dict[str, Any],
        gaps: List[Dict[str, Any]],
        forecast: Dict[str, Any],
        domain_activation: Dict[str, Any],
    ) -> str:
        """Generate PM-facing briefing document."""
        persona_pack = architecture.get("persona_archetype_pack", {})
        workflow_map = architecture.get("workflow_orchestration_map", {})
        num_archetypes = len(persona_pack.get("archetypes", []))
        num_handoffs = len(workflow_map.get("handoffs", []))
        top_gaps = sorted(gaps, key=lambda x: {"critical": 0, "warning": 1, "info": 2}.get(x.get("severity", "info"), 3))[:5]
        bottlenecks = forecast.get("bottleneck_rankings", [])[:3]

        lines = [
            "# PM Briefing",
            "",
            f"**Architecture:** {architecture.get('product_architecture_id', 'N/A')}",
            f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
            "",
            "## What You Asked For",
            f"- Intent decomposed into {num_archetypes} personas, {num_handoffs} handoffs",
            f"- Domain: {domain_activation.get('domain', 'general')} (confidence: {domain_activation.get('confidence', 0.0):.0%})",
            "",
            "## What We Built",
            f"- {len(architecture.get('artifacts', []))} artifacts generated",
            f"- {len(architecture.get('cross_links', []))} cross-layer links",
            f"- {len(architecture.get('component_prds', []))} component PRDs",
            f"- {len(architecture.get('customer_journey_maps', []))} customer journey maps",
            "",
            "## What We Found",
            f"- **Top gaps:** {len(top_gaps)} critical/warning gaps detected",
            f"- **Top bottlenecks:** {len(bottlenecks)} bottlenecks predicted",
            "",
        ]

        if top_gaps:
            lines.append("### Top Gaps\n")
            for g in top_gaps:
                lines.extend([
                    f"- **[{g['severity'].upper()}]** {g['description'][:100]}",
                    f"  - Impact: {g['impact'][:100]}",
                    f"  - Suggestion: {g['suggestion'][:100]}",
                    "",
                ])

        if bottlenecks:
            lines.append("### Top Bottlenecks\n")
            for b in bottlenecks:
                lines.append(f"- {b['impact_description'][:120]}\n")

        lines.extend([
            "## Confidence Report",
            "",
            "| Claim | Confidence | Provenance |",
            "|---|---|---|",
            f"| Domain classification | {domain_activation.get('confidence', 0.0):.0%} | observed |",
            f"| Persona identification | {num_archetypes} personas | inferred |",
            f"| Workflow handoffs | {num_handoffs} handoffs | inferred |",
            f"| Bottleneck prediction | {len(bottlenecks)} bottlenecks | simulated |",
            "",
            "## Requires Your Confirmation",
            "",
        ])

        for g in top_gaps:
            if g.get("confidence", 1.0) < 0.5:
                lines.append(f"- ⚠️ {g['description'][:100]}\n")

        if not any(g.get("confidence", 1.0) < 0.5 for g in top_gaps):
            lines.append("No low-confidence inferences requiring confirmation.\n")

        lines.extend([
            "## Next Actions",
            "1. Review gaps and accept/dismiss suggestions",
            "2. Run what-if simulation on top bottleneck",
            "3. Confirm domain activation and regions",
            "4. Review PM briefing confidence levels",
            "",
            "---",
            "*Generated by ProductOS V14 ArchitectureExporter — PM Briefing*",
        ])

        return "\n".join(lines)
